### PR TITLE
CIT - Control de permisos de prestaciones en profesionales

### PR DESCRIPTION
**Pull request by plammel**
### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-169
### Funcionalidad desarrollada 

1. Inhabilita seleccion de grupo profesional si no hay tipo de prestación seleccionada
2. Limpia selección de profesionales si cambia la selección de tipo de prestaciones
3. Incluye tipo de prestaciones en la busqueda de profesionales
4. Que pendiente de implementación el hint en el select de profesionales

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1741
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [X] Si https://github.com/andes/andes-test-integracion/pull/469
- [ ] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8413](http://condorpiedra.andes.gob.ar:85/8413/mochawesome.html)
CYPRESS RUN: [7590](https://dashboard.cypress.io/projects/xr7gft/runs/7590/specs)
TEST START: 2023-02-15T14:17:12.892Z
TOTAL: 400
SUCCESS: 383
FAIL: 15
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8416](http://condorpiedra.andes.gob.ar:85/8416/mochawesome.html)
CYPRESS RUN: [7593](https://dashboard.cypress.io/projects/xr7gft/runs/7593/specs)
TEST START: 2023-02-15T15:49:26.938Z
TOTAL: 400
SUCCESS: 390
FAIL: 8
SKIPPED: 2

**Review by negro89 — APPROVED** [review]

**Review by MarianoCampetella — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8516](http://condorpiedra.andes.gob.ar:85/8516/mochawesome.html)
CYPRESS RUN: [7695](https://dashboard.cypress.io/projects/xr7gft/runs/7695/specs)
TEST START: 2023-03-02T18:43:15.727Z
TOTAL: 400
SUCCESS: 392
FAIL: 6
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8520](http://condorpiedra.andes.gob.ar:85/8520/mochawesome.html)
CYPRESS RUN: [7699](https://dashboard.cypress.io/projects/xr7gft/runs/7699/specs)
TEST START: 2023-03-02T19:28:41.195Z
TOTAL: 392
SUCCESS: 383
FAIL: 7
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8526](http://condorpiedra.andes.gob.ar:85/8526/mochawesome.html)
CYPRESS RUN: [7705](https://dashboard.cypress.io/projects/xr7gft/runs/7705/specs)
TEST START: 2023-03-03T11:46:48.193Z
TOTAL: 400
SUCCESS: 391
FAIL: 7
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8527](http://condorpiedra.andes.gob.ar:85/8527/mochawesome.html)
CYPRESS RUN: [7706](https://dashboard.cypress.io/projects/xr7gft/runs/7706/specs)
TEST START: 2023-03-03T11:59:16.033Z
TOTAL: 400
SUCCESS: 391
FAIL: 7
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8530](http://condorpiedra.andes.gob.ar:85/8530/mochawesome.html)
CYPRESS RUN: [7709](https://dashboard.cypress.io/projects/xr7gft/runs/7709/specs)
TEST START: 2023-03-03T12:39:00.657Z
TOTAL: 400
SUCCESS: 391
FAIL: 7
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [8578](http://condorpiedra.andes.gob.ar:85/8578/mochawesome.html)
CYPRESS RUN: [7756](https://dashboard.cypress.io/projects/xr7gft/runs/7756/specs)
TEST START: 2023-03-15T11:58:02.499Z
TOTAL: 95
SUCCESS: 0
FAIL: 95
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: silviroa  
BUILD NUMBER: [8646](http://condorpiedra.andes.gob.ar:85/8646/mochawesome.html)
CYPRESS RUN: [7822](https://dashboard.cypress.io/projects/xr7gft/runs/7822/specs)
TEST START: 2023-03-30T12:51:28.601Z
TOTAL: 400
SUCCESS: 391
FAIL: 7
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: silviroa  
BUILD NUMBER: [8651](http://condorpiedra.andes.gob.ar:85/8651/mochawesome.html)
CYPRESS RUN: [7827](https://dashboard.cypress.io/projects/xr7gft/runs/7827/specs)
TEST START: 2023-03-30T14:07:21.698Z
TOTAL: 356
SUCCESS: 340
FAIL: 15
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: silviroa  
BUILD NUMBER: [8668](http://condorpiedra.andes.gob.ar:85/8668/mochawesome.html)
CYPRESS RUN: [7843](https://dashboard.cypress.io/projects/xr7gft/runs/7843/specs)
TEST START: 2023-04-03T14:08:50.349Z
TOTAL: 400
SUCCESS: 392
FAIL: 6
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8701](http://condorpiedra.andes.gob.ar:85/8701/mochawesome.html)
CYPRESS RUN: [7876](https://dashboard.cypress.io/projects/xr7gft/runs/7876/specs)
TEST START: 2023-04-13T16:53:27.198Z
TOTAL: 400
SUCCESS: 392
FAIL: 6
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8718](http://condorpiedra.andes.gob.ar:85/8718/mochawesome.html)
CYPRESS RUN: [7893](https://dashboard.cypress.io/projects/xr7gft/runs/7893/specs)
TEST START: 2023-04-17T17:12:34.664Z
TOTAL: 406
SUCCESS: 399
FAIL: 5
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8720](http://condorpiedra.andes.gob.ar:85/8720/mochawesome.html)
CYPRESS RUN: [7895](https://dashboard.cypress.io/projects/xr7gft/runs/7895/specs)
TEST START: 2023-04-18T13:43:42.799Z
TOTAL: 393
SUCCESS: 389
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8734](http://condorpiedra.andes.gob.ar:85/8734/mochawesome.html)
CYPRESS RUN: [7909](https://dashboard.cypress.io/projects/xr7gft/runs/7909/specs)
TEST START: 2023-04-20T14:10:53.935Z
TOTAL: 397
SUCCESS: 394
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8754](http://condorpiedra.andes.gob.ar:85/8754/mochawesome.html)
CYPRESS RUN: [7928](https://dashboard.cypress.io/projects/xr7gft/runs/7928/specs)
TEST START: 2023-04-25T14:43:38.438Z
TOTAL: 323
SUCCESS: 312
FAIL: 9
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8755](http://condorpiedra.andes.gob.ar:85/8755/mochawesome.html)
CYPRESS RUN: [7929](https://dashboard.cypress.io/projects/xr7gft/runs/7929/specs)
TEST START: 2023-04-25T14:58:48.803Z
TOTAL: 330
SUCCESS: 320
FAIL: 8
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8816](http://condorpiedra.andes.gob.ar:85/8816/mochawesome.html)
CYPRESS RUN: [7986](https://dashboard.cypress.io/projects/xr7gft/runs/7986/specs)
TEST START: 2023-05-02T21:17:23.224Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8817](http://condorpiedra.andes.gob.ar:85/8817/mochawesome.html)
CYPRESS RUN: [7987](https://dashboard.cypress.io/projects/xr7gft/runs/7987/specs)
TEST START: 2023-05-02T21:41:57.451Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8820](http://condorpiedra.andes.gob.ar:85/8820/mochawesome.html)
CYPRESS RUN: [7989](https://dashboard.cypress.io/projects/xr7gft/runs/7989/specs)
TEST START: 2023-05-03T12:14:34.194Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8821](http://condorpiedra.andes.gob.ar:85/8821/mochawesome.html)
CYPRESS RUN: [7990](https://dashboard.cypress.io/projects/xr7gft/runs/7990/specs)
TEST START: 2023-05-03T12:32:53.201Z
TOTAL: 340
SUCCESS: 322
FAIL: 16
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8826](http://condorpiedra.andes.gob.ar:85/8826/mochawesome.html)
CYPRESS RUN: [7995](https://dashboard.cypress.io/projects/xr7gft/runs/7995/specs)
TEST START: 2023-05-04T12:46:09.869Z
TOTAL: 350
SUCCESS: 340
FAIL: 8
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8835](http://condorpiedra.andes.gob.ar:85/8835/mochawesome.html)
CYPRESS RUN: [8004](https://dashboard.cypress.io/projects/xr7gft/runs/8004/specs)
TEST START: 2023-05-04T17:35:29.545Z
TOTAL: 361
SUCCESS: 352
FAIL: 8
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8838](http://condorpiedra.andes.gob.ar:85/8838/mochawesome.html)
CYPRESS RUN: [8007](https://dashboard.cypress.io/projects/xr7gft/runs/8007/specs)
TEST START: 2023-05-04T19:16:33.512Z
TOTAL: 400
SUCCESS: 392
FAIL: 6
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8841](http://condorpiedra.andes.gob.ar:85/8841/mochawesome.html)
CYPRESS RUN: [8009](https://dashboard.cypress.io/projects/xr7gft/runs/8009/specs)
TEST START: 2023-05-05T12:38:23.127Z
TOTAL: 406
SUCCESS: 401
FAIL: 3
SKIPPED: 2

**Comment by negro89** [comment]
@silviroa quería revisarlo

**Comment by silviroa** [comment]
USUARIO: silviroa  
BUILD NUMBER: [8897](http://condorpiedra.andes.gob.ar:85/8897/mochawesome.html)
CYPRESS RUN: [8062](https://dashboard.cypress.io/projects/xr7gft/runs/8062/specs)
TEST START: 2023-05-15T17:36:47.141Z
TOTAL: 400
SUCCESS: 393
FAIL: 5
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8945](http://condorpiedra.andes.gob.ar:85/8945/mochawesome.html)
CYPRESS RUN: [8108](https://dashboard.cypress.io/projects/xr7gft/runs/8108/specs)
TEST START: 2023-05-24T12:29:17.289Z
TOTAL: 400
SUCCESS: 394
FAIL: 4
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8946](http://condorpiedra.andes.gob.ar:85/8946/mochawesome.html)
CYPRESS RUN: [8109](https://dashboard.cypress.io/projects/xr7gft/runs/8109/specs)
TEST START: 2023-05-24T12:50:22.058Z
TOTAL: 400
SUCCESS: 394
FAIL: 4
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8949](http://condorpiedra.andes.gob.ar:85/8949/mochawesome.html)
CYPRESS RUN: [8112](https://dashboard.cypress.io/projects/xr7gft/runs/8112/specs)
TEST START: 2023-05-24T17:12:48.255Z
TOTAL: 400
SUCCESS: 394
FAIL: 4
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8956](http://condorpiedra.andes.gob.ar:85/8956/mochawesome.html)
CYPRESS RUN: [8119](https://dashboard.cypress.io/projects/xr7gft/runs/8119/specs)
TEST START: 2023-05-29T15:12:29.239Z
TOTAL: 400
SUCCESS: 394
FAIL: 4
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8957](http://condorpiedra.andes.gob.ar:85/8957/mochawesome.html)
CYPRESS RUN: [8120](https://dashboard.cypress.io/projects/xr7gft/runs/8120/specs)
TEST START: 2023-05-29T15:28:35.360Z
TOTAL: 400
SUCCESS: 394
FAIL: 4
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8961](http://condorpiedra.andes.gob.ar:85/8961/mochawesome.html)
CYPRESS RUN: [8124](https://dashboard.cypress.io/projects/xr7gft/runs/8124/specs)
TEST START: 2023-05-29T18:56:26.777Z
TOTAL: 400
SUCCESS: 394
FAIL: 4
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8973](http://condorpiedra.andes.gob.ar:85/8973/mochawesome.html)
CYPRESS RUN: [8136](https://dashboard.cypress.io/projects/xr7gft/runs/8136/specs)
TEST START: 2023-05-31T15:52:57.997Z
TOTAL: 400
SUCCESS: 392
FAIL: 6
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [8974](http://condorpiedra.andes.gob.ar:85/8974/mochawesome.html)
CYPRESS RUN: [8137](https://dashboard.cypress.io/projects/xr7gft/runs/8137/specs)
TEST START: 2023-05-31T16:44:47.214Z
TOTAL: 400
SUCCESS: 391
FAIL: 7
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9004](http://condorpiedra.andes.gob.ar:85/9004/mochawesome.html)
CYPRESS RUN: [8164](https://dashboard.cypress.io/projects/xr7gft/runs/8164/specs)
TEST START: 2023-06-06T14:05:57.063Z
TOTAL: 395
SUCCESS: 383
FAIL: 10
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9007](http://condorpiedra.andes.gob.ar:85/9007/mochawesome.html)
CYPRESS RUN: [8167](https://dashboard.cypress.io/projects/xr7gft/runs/8167/specs)
TEST START: 2023-06-06T14:51:59.867Z
TOTAL: 397
SUCCESS: 390
FAIL: 5
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9009](http://condorpiedra.andes.gob.ar:85/9009/mochawesome.html)
CYPRESS RUN: [8169](https://dashboard.cypress.io/projects/xr7gft/runs/8169/specs)
TEST START: 2023-06-06T15:48:52.327Z
TOTAL: 397
SUCCESS: 389
FAIL: 6
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9041](http://condorpiedra.andes.gob.ar:85/9041/mochawesome.html)
CYPRESS RUN: [8199](https://dashboard.cypress.io/projects/xr7gft/runs/8199/specs)
TEST START: 2023-06-08T17:52:12.435Z
TOTAL: 398
SUCCESS: 389
FAIL: 7
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9042](http://condorpiedra.andes.gob.ar:85/9042/mochawesome.html)
CYPRESS RUN: [8200](https://dashboard.cypress.io/projects/xr7gft/runs/8200/specs)
TEST START: 2023-06-08T18:17:54.383Z
TOTAL: 398
SUCCESS: 388
FAIL: 8
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9050](http://condorpiedra.andes.gob.ar:85/9050/mochawesome.html)
CYPRESS RUN: [8208](https://dashboard.cypress.io/projects/xr7gft/runs/8208/specs)
TEST START: 2023-06-09T15:59:14.010Z
TOTAL: 398
SUCCESS: 389
FAIL: 7
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9065](http://condorpiedra.andes.gob.ar:85/9065/mochawesome.html)
CYPRESS RUN: [8223](https://dashboard.cypress.io/projects/xr7gft/runs/8223/specs)
TEST START: 2023-06-12T13:14:57.004Z
TOTAL: 398
SUCCESS: 391
FAIL: 5
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9067](http://condorpiedra.andes.gob.ar:85/9067/mochawesome.html)
CYPRESS RUN: [8225](https://dashboard.cypress.io/projects/xr7gft/runs/8225/specs)
TEST START: 2023-06-12T13:55:52.455Z
TOTAL: 398
SUCCESS: 392
FAIL: 4
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9144](http://condorpiedra.andes.gob.ar:85/9144/mochawesome.html)
CYPRESS RUN: [8291](https://dashboard.cypress.io/projects/xr7gft/runs/8291/specs)
TEST START: 2023-06-30T17:18:11.505Z
TOTAL: 398
SUCCESS: 392
FAIL: 4
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9145](http://condorpiedra.andes.gob.ar:85/9145/mochawesome.html)
CYPRESS RUN: [8292](https://dashboard.cypress.io/projects/xr7gft/runs/8292/specs)
TEST START: 2023-06-30T17:39:26.337Z
TOTAL: 398
SUCCESS: 389
FAIL: 7
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9385](http://condorpiedra.andes.gob.ar:85/9385/mochawesome.html)
CYPRESS RUN: [8522](https://dashboard.cypress.io/projects/xr7gft/runs/8522/specs)
TEST START: 2023-08-10T16:17:08.599Z
TOTAL: 399
SUCCESS: 393
FAIL: 4
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9386](http://condorpiedra.andes.gob.ar:85/9386/mochawesome.html)
CYPRESS RUN: [8523](https://dashboard.cypress.io/projects/xr7gft/runs/8523/specs)
TEST START: 2023-08-10T16:46:42.867Z
TOTAL: 360
SUCCESS: 343
FAIL: 15
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9389](http://condorpiedra.andes.gob.ar:85/9389/mochawesome.html)
CYPRESS RUN: [8526](https://dashboard.cypress.io/projects/xr7gft/runs/8526/specs)
TEST START: 2023-08-11T12:39:02.473Z
TOTAL: 363
SUCCESS: 352
FAIL: 9
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9390](http://condorpiedra.andes.gob.ar:85/9390/mochawesome.html)
CYPRESS RUN: [8527](https://dashboard.cypress.io/projects/xr7gft/runs/8527/specs)
TEST START: 2023-08-11T13:25:29.298Z
TOTAL: 400
SUCCESS: 396
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9391](http://condorpiedra.andes.gob.ar:85/9391/mochawesome.html)
CYPRESS RUN: [8528](https://dashboard.cypress.io/projects/xr7gft/runs/8528/specs)
TEST START: 2023-08-11T14:09:03.271Z
TOTAL: 367
SUCCESS: 357
FAIL: 8
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9394](http://condorpiedra.andes.gob.ar:85/9394/mochawesome.html)
CYPRESS RUN: [8531](https://dashboard.cypress.io/projects/xr7gft/runs/8531/specs)
TEST START: 2023-08-11T15:13:37.890Z
TOTAL: 400
SUCCESS: 396
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9398](http://condorpiedra.andes.gob.ar:85/9398/mochawesome.html)
CYPRESS RUN: [8535](https://dashboard.cypress.io/projects/xr7gft/runs/8535/specs)
TEST START: 2023-08-11T19:09:40.311Z
TOTAL: 361
SUCCESS: 343
FAIL: 16
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9403](http://condorpiedra.andes.gob.ar:85/9403/mochawesome.html)
CYPRESS RUN: [8540](https://dashboard.cypress.io/projects/xr7gft/runs/8540/specs)
TEST START: 2023-08-14T13:49:09.928Z
TOTAL: 400
SUCCESS: 397
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9415](http://condorpiedra.andes.gob.ar:85/9415/mochawesome.html)
CYPRESS RUN: [8552](https://dashboard.cypress.io/projects/xr7gft/runs/8552/specs)
TEST START: 2023-08-14T17:09:25.511Z
TOTAL: 400
SUCCESS: 397
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9420](http://condorpiedra.andes.gob.ar:85/9420/mochawesome.html)
CYPRESS RUN: [8557](https://dashboard.cypress.io/projects/xr7gft/runs/8557/specs)
TEST START: 2023-08-15T12:18:50.014Z
TOTAL: 396
SUCCESS: 391
FAIL: 3
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [9473](http://condorpiedra.andes.gob.ar:85/9473/mochawesome.html)
CYPRESS RUN: [8600](https://dashboard.cypress.io/projects/xr7gft/runs/8600/specs)
TEST START: 2023-08-18T12:54:57.327Z
TOTAL: 400
SUCCESS: 396
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9592](http://condorpiedra.andes.gob.ar:85/9592/mochawesome.html)
CYPRESS RUN: [8710](https://dashboard.cypress.io/projects/xr7gft/runs/8710/specs)
TEST START: 2023-09-11T14:01:10.835Z
TOTAL: 400
SUCCESS: 396
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9613](http://condorpiedra.andes.gob.ar:85/9613/mochawesome.html)
CYPRESS RUN: [8729](https://dashboard.cypress.io/projects/xr7gft/runs/8729/specs)
TEST START: 2023-09-13T17:42:51.196Z
TOTAL: 330
SUCCESS: 311
FAIL: 17
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9614](http://condorpiedra.andes.gob.ar:85/9614/mochawesome.html)
CYPRESS RUN: [8730](https://dashboard.cypress.io/projects/xr7gft/runs/8730/specs)
TEST START: 2023-09-13T17:54:41.106Z
TOTAL: 400
SUCCESS: 396
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9615](http://condorpiedra.andes.gob.ar:85/9615/mochawesome.html)
CYPRESS RUN: [8731](https://dashboard.cypress.io/projects/xr7gft/runs/8731/specs)
TEST START: 2023-09-13T18:26:46.759Z
TOTAL: 95
SUCCESS: 0
FAIL: 95
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9616](http://condorpiedra.andes.gob.ar:85/9616/mochawesome.html)
CYPRESS RUN: [8732](https://dashboard.cypress.io/projects/xr7gft/runs/8732/specs)
TEST START: 2023-09-13T18:38:42.365Z
TOTAL: 400
SUCCESS: 396
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9617](http://condorpiedra.andes.gob.ar:85/9617/mochawesome.html)
CYPRESS RUN: [8733](https://dashboard.cypress.io/projects/xr7gft/runs/8733/specs)
TEST START: 2023-09-13T19:08:29.249Z
TOTAL: 400
SUCCESS: 397
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9631](http://condorpiedra.andes.gob.ar:85/9631/mochawesome.html)
CYPRESS RUN: [8747](https://dashboard.cypress.io/projects/xr7gft/runs/8747/specs)
TEST START: 2023-09-14T19:17:42.962Z
TOTAL: 400
SUCCESS: 397
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9647](http://condorpiedra.andes.gob.ar:85/9647/mochawesome.html)
CYPRESS RUN: [8761](https://dashboard.cypress.io/projects/xr7gft/runs/8761/specs)
TEST START: 2023-09-21T18:25:34.808Z
TOTAL: 400
SUCCESS: 397
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mbenicio  
BUILD NUMBER: [9663](http://condorpiedra.andes.gob.ar:85/9663/mochawesome.html)
CYPRESS RUN: [8777](https://dashboard.cypress.io/projects/xr7gft/runs/8777/specs)
TEST START: 2023-09-26T16:45:48.252Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Comment by maring0019** [comment]
> Hay que revisar los test de crear agenda y dar turnos (desde ventanilla y desde solicitudes)

Se realizaron cambios en test que daban error en Jenkis.

**Pull request merged**
