### PR TITLE
ANGULAR 9 update

### PR DESCRIPTION
**Pull request by liquid36**
### Requerimiento
Actualizar a angular 9 y después al 10.

### UserStory llegó a completarse
- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [x] No

### Requiere actualizaciones en la API
- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion
- [ ] Si
- [x] No

### CODE REVIEW

**Comment by liquid36** [comment]
BUILD NUMBER: 1628
TEST START: 2020-09-01T14:45:00.361Z
TOTAL: 299
SUCCESS: 292
FAIL: 3
SKIPPED: 4

**Comment by liquid36** [comment]
BUILD NUMBER: 1639
TEST START: 2020-09-01T20:06:12.723Z
TOTAL: 258
SUCCESS: 190
FAIL: 64
SKIPPED: 4

**Comment by liquid36** [comment]
BUILD NUMBER: 1681
TEST START: 2020-09-04T18:33:54.735Z
TOTAL: 295
SUCCESS: 289
FAIL: 2
SKIPPED: 4

**Comment by liquid36** [comment]
BUILD NUMBER: 1682
TEST START: 2020-09-04T18:43:54.179Z
TOTAL: 299
SUCCESS: 21
FAIL: 0
SKIPPED: 278

**Comment by liquid36** [comment]
BUILD NUMBER: 1683
TEST START: 2020-09-04T19:22:21.457Z
TOTAL: 299
SUCCESS: 289
FAIL: 6
SKIPPED: 4

**Comment by liquid36** [comment]
BUILD NUMBER: 1684
TEST START: 2020-09-04T19:33:25.158Z
TOTAL: 299
SUCCESS: 288
FAIL: 7
SKIPPED: 4

**Comment by liquid36** [comment]
BUILD NUMBER: 1731
TEST START: 2020-09-09T17:01:28.566Z
TOTAL: 282
SUCCESS: 277
FAIL: 1
SKIPPED: 4

**Comment by liquid36** [comment]
BUILD NUMBER: 1732
TEST START: 2020-09-09T17:09:41.242Z
TOTAL: 274
SUCCESS: 2
FAIL: 1
SKIPPED: 271

**Comment by liquid36** [comment]
BUILD NUMBER: 1739
TEST START: 2020-09-10T14:43:21.730Z
TOTAL: 231
SUCCESS: 229
FAIL: 1
SKIPPED: 1

**Comment by liquid36** [comment]
BUILD NUMBER: 1740
TEST START: 2020-09-10T14:48:39.518Z
TOTAL: 6
SUCCESS: 6
FAIL: 0
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: 1741
TEST START: 2020-09-10T14:50:48.749Z
TOTAL: 20
SUCCESS: 19
FAIL: 0
SKIPPED: 1

**Comment by liquid36** [comment]
BUILD NUMBER: 1742
TEST START: 2020-09-10T14:54:19.364Z
TOTAL: 3
SUCCESS: 3
FAIL: 0
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: 1745
TEST START: 2020-09-10T15:01:47.887Z
TOTAL: 2
SUCCESS: 1
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: 1746
TEST START: 2020-09-10T15:22:24.594Z
TOTAL: 1
SUCCESS: 1
FAIL: 0
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: 1747
TEST START: 2020-09-10T15:24:35.306Z
TOTAL: 5
SUCCESS: 5
FAIL: 0
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: 1749
TEST START: 2020-09-10T15:30:54.746Z
TOTAL: 3
SUCCESS: 3
FAIL: 0
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: 1750
TEST START: 2020-09-10T15:33:25.317Z
TOTAL: 3
SUCCESS: 3
FAIL: 0
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: 1751
TEST START: 2020-09-10T15:35:54.350Z
TOTAL: 9
SUCCESS: 9
FAIL: 0
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: 1752
TEST START: 2020-09-10T15:39:05.628Z
TOTAL: 6
SUCCESS: 6
FAIL: 0
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: 1753
TEST START: 2020-09-10T15:41:15.152Z
TOTAL: 2
SUCCESS: 2
FAIL: 0
SKIPPED: 0

**Review by palita1991 — APPROVED** [review]
Revisar el único test que falló, https://dashboard.cypress.io/projects/xr7gft/runs/980/failures . Pero lo demas :+1:

**Comment by liquid36** [comment]
BUILD NUMBER: 1755
TEST START: 2020-09-10T17:29:55.585Z
TOTAL: 2
SUCCESS: 1
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: 1756
TEST START: 2020-09-10T17:35:05.196Z
TOTAL: 2
SUCCESS: 1
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: 1757
TEST START: 2020-09-10T18:02:18.244Z
TOTAL: 2
SUCCESS: 1
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: 1758
TEST START: 2020-09-10T18:11:59.944Z
TOTAL: 2
SUCCESS: 2
FAIL: 0
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: 1759
TEST START: 2020-09-10T18:23:23.566Z
TOTAL: 290
SUCCESS: 288
FAIL: 0
SKIPPED: 2

**Comment by liquid36** [comment]
BUILD NUMBER: 1764
TEST START: undefined
TOTAL: 0
SUCCESS: 0
FAIL: 0
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: 1765
TEST START: undefined
TOTAL: 0
SUCCESS: 0
FAIL: 0
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: [1790](http://condorpiedra.andes.gob.ar:85/1790/mochawesome.html)
TEST START: 2020-09-13T17:29:40.270Z
TOTAL: 297
SUCCESS: 283
FAIL: 13
SKIPPED: 1

**Comment by liquid36** [comment]
BUILD NUMBER: [1791](http://condorpiedra.andes.gob.ar:85/1791/mochawesome.html)
TEST START: 2020-09-13T18:13:58.070Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

**Review by kroce — APPROVED** [review]

**Comment by liquid36** [comment]
BUILD NUMBER: [1804](http://condorpiedra.andes.gob.ar:85/1804/mochawesome.html)
TEST START: 2020-09-15T15:13:23.139Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

**Pull request merged**
