### PR TITLE
CIT: fix frecuentes duplicados

### PR DESCRIPTION
**Pull request by plammel**
### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-152
### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

### CODE REVIEW

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [5599](http://condorpiedra.andes.gob.ar:85/5599/mochawesome.html)
CYPRESS RUN: [4534](https://dashboard.cypress.io/projects/xr7gft/runs/4534/specs)
TEST START: 2021-12-13T16:38:06.028Z
TOTAL: 402
SUCCESS: 400
FAIL: 1
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [5600](http://condorpiedra.andes.gob.ar:85/5600/mochawesome.html)
CYPRESS RUN: [4535](https://dashboard.cypress.io/projects/xr7gft/runs/4535/specs)
TEST START: 2021-12-13T16:56:46.207Z
TOTAL: 342
SUCCESS: 329
FAIL: 12
SKIPPED: 1

**Review by liquid36 — APPROVED** [review]

**Review by martinebucarey — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [5602](http://condorpiedra.andes.gob.ar:85/5602/mochawesome.html)
CYPRESS RUN: [4537](https://dashboard.cypress.io/projects/xr7gft/runs/4537/specs)
TEST START: 2021-12-13T18:16:29.008Z
TOTAL: 402
SUCCESS: 400
FAIL: 1
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [5603](http://condorpiedra.andes.gob.ar:85/5603/mochawesome.html)
CYPRESS RUN: [4538](https://dashboard.cypress.io/projects/xr7gft/runs/4538/specs)
TEST START: 2021-12-13T18:29:50.892Z
TOTAL: 402
SUCCESS: 401
FAIL: 0
SKIPPED: 1

**Pull request merged**
