### PR TITLE
EP: resize sidebar paciente

### PR DESCRIPTION
**Pull request by plammel**
### Requerimiento
 
https://proyectos.andes.gob.ar/browse/EP-97
### Funcionalidad desarrollada 

1. Resize de sidebar de paciente en carga de ficha
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

### CODE REVIEW

**Review by sychus — APPROVED** [review]

**Review by martinebucarey — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: hfernandez  
BUILD NUMBER: [4481](http://condorpiedra.andes.gob.ar:85/4481/mochawesome.html)
CYPRESS RUN: [3500](https://dashboard.cypress.io/projects/xr7gft/runs/3500/specs)
TEST START: 2021-07-02T15:32:11.945Z
TOTAL: 380
SUCCESS: 378
FAIL: 1
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [4488](http://condorpiedra.andes.gob.ar:85/4488/mochawesome.html)
CYPRESS RUN: [3507](https://dashboard.cypress.io/projects/xr7gft/runs/3507/specs)
TEST START: 2021-07-02T17:47:48.797Z
TOTAL: 356
SUCCESS: 343
FAIL: 12
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [4508](http://condorpiedra.andes.gob.ar:85/4508/mochawesome.html)
CYPRESS RUN: [3527](https://dashboard.cypress.io/projects/xr7gft/runs/3527/specs)
TEST START: 2021-07-07T15:13:35.093Z
TOTAL: 403
SUCCESS: 398
FAIL: 4
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [4526](http://condorpiedra.andes.gob.ar:85/4526/mochawesome.html)
CYPRESS RUN: [3545](https://dashboard.cypress.io/projects/xr7gft/runs/3545/specs)
TEST START: 2021-07-08T13:24:43.822Z
TOTAL: 326
SUCCESS: 312
FAIL: 13
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [4527](http://condorpiedra.andes.gob.ar:85/4527/mochawesome.html)
CYPRESS RUN: [3546](https://dashboard.cypress.io/projects/xr7gft/runs/3546/specs)
TEST START: 2021-07-08T13:43:12.845Z
TOTAL: 403
SUCCESS: 402
FAIL: 0
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [4585](http://condorpiedra.andes.gob.ar:85/4585/mochawesome.html)
CYPRESS RUN: [3596](https://dashboard.cypress.io/projects/xr7gft/runs/3596/specs)
TEST START: 2021-07-15T14:00:43.164Z
TOTAL: 399
SUCCESS: 398
FAIL: 0
SKIPPED: 1

**Pull request merged**
