### PR TITLE
feat(solicitudes): agrega nuevo pipe para unificar controles 

### PR DESCRIPTION
**Pull request by kroce**
### Requerimiento
 Agrega nuevo pipe para unificar controles en los botones de las operaciones

### Funcionalidad desarrollada 

1. Se agrega pipe BotonesSolicitudPipe en módulo TOP
2. Se eliminan arrays de solicitudes de entrada/salida que ya no se utilizaban
3. Se modifica html con nuevas condiciones

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [x] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [x] Si https://github.com/andes/andes-test-integracion/pull/282
- [ ] No

### CODE REVIEW

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [2395](http://condorpiedra.andes.gob.ar:85/2395/mochawesome.html)
CYPRESS RUN: [1562](https://dashboard.cypress.io/projects/xr7gft/runs/1562/specs)
TEST START: 2020-10-28T15:27:39.478Z
TOTAL: 329
SUCCESS: 324
FAIL: 5
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [2421](http://condorpiedra.andes.gob.ar:85/2421/mochawesome.html)
CYPRESS RUN: [1588](https://dashboard.cypress.io/projects/xr7gft/runs/1588/specs)
TEST START: 2020-10-29T13:14:55.994Z
TOTAL: 334
SUCCESS: 331
FAIL: 3
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: cceleste  
BUILD NUMBER: [2439](http://condorpiedra.andes.gob.ar:85/2439/mochawesome.html)
CYPRESS RUN: [1606](https://dashboard.cypress.io/projects/xr7gft/runs/1606/specs)
TEST START: 2020-10-29T17:58:43.397Z
TOTAL: 329
SUCCESS: 329
FAIL: 0
SKIPPED: 0

**Review by liquid36 — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: cceleste  
BUILD NUMBER: [2456](http://condorpiedra.andes.gob.ar:85/2456/mochawesome.html)
CYPRESS RUN: [1620](https://dashboard.cypress.io/projects/xr7gft/runs/1620/specs)
TEST START: 2020-10-30T13:01:26.317Z
TOTAL: 333
SUCCESS: 332
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: cceleste  
BUILD NUMBER: [2457](http://condorpiedra.andes.gob.ar:85/2457/mochawesome.html)
CYPRESS RUN: [1621](https://dashboard.cypress.io/projects/xr7gft/runs/1621/specs)
TEST START: 2020-10-30T13:09:00.882Z
TOTAL: 2
SUCCESS: 2
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by liquid36** [comment]
USUARIO: cceleste  
BUILD NUMBER: [2458](http://condorpiedra.andes.gob.ar:85/2458/mochawesome.html)
CYPRESS RUN: [1622](https://dashboard.cypress.io/projects/xr7gft/runs/1622/specs)
TEST START: 2020-10-30T13:26:31.117Z
TOTAL: 315
SUCCESS: 314
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: cceleste  
BUILD NUMBER: [2459](http://condorpiedra.andes.gob.ar:85/2459/mochawesome.html)
CYPRESS RUN: [1623](https://dashboard.cypress.io/projects/xr7gft/runs/1623/specs)
TEST START: 2020-10-30T13:30:40.602Z
TOTAL: 19
SUCCESS: 19
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Review by palita1991 — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [2460](http://condorpiedra.andes.gob.ar:85/2460/mochawesome.html)
CYPRESS RUN: [1624](https://dashboard.cypress.io/projects/xr7gft/runs/1624/specs)
TEST START: 2020-10-30T13:56:02.478Z
TOTAL: 333
SUCCESS: 332
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [2462](http://condorpiedra.andes.gob.ar:85/2462/mochawesome.html)
CYPRESS RUN: [1626](https://dashboard.cypress.io/projects/xr7gft/runs/1626/specs)
TEST START: 2020-10-30T14:55:37.733Z
TOTAL: 333
SUCCESS: 333
FAIL: 0
SKIPPED: 0

**Pull request merged**
