### PR TITLE
rup: conceptos requeridos dinámicos

### PR DESCRIPTION
**Pull request by liquid36**
### Requerimiento

https://proyectos.andes.gob.ar/browse/RUP-255

### Funcionalidad desarrollada  
1. 
2. 
3. 

### UserStory llegó a completarse 
- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos 
- [ ] Si
- [x] No

### Requiere actualizaciones en la API 
- [x] Si https://github.com/andes/api/pull/1427
- [ ] No

### Requiere actualizaciones en andes-test-integracion 
- [ ] Si
- [x] No

### CODE REVIEW

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [4338](http://condorpiedra.andes.gob.ar:85/4338/mochawesome.html)
CYPRESS RUN: [3361](https://dashboard.cypress.io/projects/xr7gft/runs/3361/specs)
TEST START: 2021-06-14T11:29:50.899Z
TOTAL: 396
SUCCESS: 395
FAIL: 0
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [4341](http://condorpiedra.andes.gob.ar:85/4341/mochawesome.html)
CYPRESS RUN: [3364](https://dashboard.cypress.io/projects/xr7gft/runs/3364/specs)
TEST START: 2021-06-14T17:20:29.242Z
TOTAL: 399
SUCCESS: 398
FAIL: 0
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [4347](http://condorpiedra.andes.gob.ar:85/4347/mochawesome.html)
CYPRESS RUN: [3370](https://dashboard.cypress.io/projects/xr7gft/runs/3370/specs)
TEST START: 2021-06-15T12:41:23.147Z
TOTAL: 399
SUCCESS: 391
FAIL: 7
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [4348](http://condorpiedra.andes.gob.ar:85/4348/mochawesome.html)
CYPRESS RUN: [3371](https://dashboard.cypress.io/projects/xr7gft/runs/3371/specs)
TEST START: 2021-06-15T12:50:59.357Z
TOTAL: 399
SUCCESS: 398
FAIL: 0
SKIPPED: 1

**Review by negro89 — APPROVED** [review]

**Review by condorpiedra — APPROVED** [review]

**Review by MCele — APPROVED** [review]

**Pull request merged**
