### PR TITLE
IN - controles para pacientes duplicados en camas distintas

### PR DESCRIPTION
**Pull request by MarianoCampetella**
### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-489

### Funcionalidad desarrollada 

1. Se agrego un setFecha para que en primera instancia actualice el mapa de camas antes de realizar un movimiento y con este mismo va a saber si la cama se encuentra o no disponible para realizar un cambio. También se agregaron múltiples controles al momento de guardar un cambio o pase de UO para evitar duplicados o movimientos que no corresponden.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

Nota: anteriormente requería los cambios en la api, pero como no son necesarios se procede a cerrar el PR. 

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [7998](http://condorpiedra.andes.gob.ar:85/7998/mochawesome.html)
CYPRESS RUN: [7191](https://dashboard.cypress.io/projects/xr7gft/runs/7191/specs)
TEST START: 2022-11-23T16:32:39.443Z
TOTAL: 406
SUCCESS: 402
FAIL: 3
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [7999](http://condorpiedra.andes.gob.ar:85/7999/mochawesome.html)
CYPRESS RUN: [7192](https://dashboard.cypress.io/projects/xr7gft/runs/7192/specs)
TEST START: 2022-11-23T17:14:35.783Z
TOTAL: 406
SUCCESS: 396
FAIL: 9
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [8000](http://condorpiedra.andes.gob.ar:85/8000/mochawesome.html)
CYPRESS RUN: [7193](https://dashboard.cypress.io/projects/xr7gft/runs/7193/specs)
TEST START: 2022-11-23T17:25:58.805Z
TOTAL: 406
SUCCESS: 402
FAIL: 3
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [8056](http://condorpiedra.andes.gob.ar:85/8056/mochawesome.html)
CYPRESS RUN: [7248](https://dashboard.cypress.io/projects/xr7gft/runs/7248/specs)
TEST START: 2022-12-01T16:18:24.470Z
TOTAL: 376
SUCCESS: 358
FAIL: 16
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [8057](http://condorpiedra.andes.gob.ar:85/8057/mochawesome.html)
CYPRESS RUN: [7249](https://dashboard.cypress.io/projects/xr7gft/runs/7249/specs)
TEST START: 2022-12-01T16:41:33.804Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [8058](http://condorpiedra.andes.gob.ar:85/8058/mochawesome.html)
CYPRESS RUN: [7250](https://dashboard.cypress.io/projects/xr7gft/runs/7250/specs)
TEST START: 2022-12-01T17:05:03.485Z
TOTAL: 406
SUCCESS: 386
FAIL: 18
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [8059](http://condorpiedra.andes.gob.ar:85/8059/mochawesome.html)
CYPRESS RUN: [7251](https://dashboard.cypress.io/projects/xr7gft/runs/7251/specs)
TEST START: 2022-12-01T18:13:50.377Z
TOTAL: 406
SUCCESS: 395
FAIL: 9
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [8060](http://condorpiedra.andes.gob.ar:85/8060/mochawesome.html)
CYPRESS RUN: [7252](https://dashboard.cypress.io/projects/xr7gft/runs/7252/specs)
TEST START: 2022-12-01T19:01:11.638Z
TOTAL: 374
SUCCESS: 365
FAIL: 7
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [8076](http://condorpiedra.andes.gob.ar:85/8076/mochawesome.html)
CYPRESS RUN: [7268](https://dashboard.cypress.io/projects/xr7gft/runs/7268/specs)
TEST START: 2022-12-05T12:00:22.955Z
TOTAL: 369
SUCCESS: 359
FAIL: 8
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [8078](http://condorpiedra.andes.gob.ar:85/8078/mochawesome.html)
CYPRESS RUN: [7270](https://dashboard.cypress.io/projects/xr7gft/runs/7270/specs)
TEST START: 2022-12-05T12:26:40.006Z
TOTAL: 406
SUCCESS: 396
FAIL: 8
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [8079](http://condorpiedra.andes.gob.ar:85/8079/mochawesome.html)
CYPRESS RUN: [7271](https://dashboard.cypress.io/projects/xr7gft/runs/7271/specs)
TEST START: 2022-12-05T12:38:30.286Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [8080](http://condorpiedra.andes.gob.ar:85/8080/mochawesome.html)
CYPRESS RUN: [7272](https://dashboard.cypress.io/projects/xr7gft/runs/7272/specs)
TEST START: 2022-12-05T13:47:33.616Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [8090](http://condorpiedra.andes.gob.ar:85/8090/mochawesome.html)
CYPRESS RUN: [7282](https://dashboard.cypress.io/projects/xr7gft/runs/7282/specs)
TEST START: 2022-12-06T12:49:31.927Z
TOTAL: 406
SUCCESS: 397
FAIL: 7
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [8092](http://condorpiedra.andes.gob.ar:85/8092/mochawesome.html)
CYPRESS RUN: [7284](https://dashboard.cypress.io/projects/xr7gft/runs/7284/specs)
TEST START: 2022-12-06T13:30:54.418Z
TOTAL: 406
SUCCESS: 396
FAIL: 8
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [8094](http://condorpiedra.andes.gob.ar:85/8094/mochawesome.html)
CYPRESS RUN: [7286](https://dashboard.cypress.io/projects/xr7gft/runs/7286/specs)
TEST START: 2022-12-06T14:07:07.336Z
TOTAL: 348
SUCCESS: 331
FAIL: 15
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [8096](http://condorpiedra.andes.gob.ar:85/8096/mochawesome.html)
CYPRESS RUN: [7288](https://dashboard.cypress.io/projects/xr7gft/runs/7288/specs)
TEST START: 2022-12-06T14:35:35.490Z
TOTAL: 406
SUCCESS: 396
FAIL: 8
SKIPPED: 2

**Comment by MarianoCampetella** [comment]
Según lo charlado previamente, se aplican los controles que ya existen en la app para saber si se puede o no cambiar de cama (evitando pacientes duplicados y que el historial tenga movimientos que no correspondan). Ademas se procede a cerrar el pr asociado a esta tarea que se encuentra en la api ya que no es necesario los cambios realizados.

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [8248](http://condorpiedra.andes.gob.ar:85/8248/mochawesome.html)
CYPRESS RUN: [7429](https://dashboard.cypress.io/projects/xr7gft/runs/7429/specs)
TEST START: 2023-01-12T17:51:47.801Z
TOTAL: 406
SUCCESS: 395
FAIL: 9
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [8252](http://condorpiedra.andes.gob.ar:85/8252/mochawesome.html)
CYPRESS RUN: [7433](https://dashboard.cypress.io/projects/xr7gft/runs/7433/specs)
TEST START: 2023-01-13T15:22:25.525Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

**Review by negro89 — APPROVED** [review]

**Review by silviroa — APPROVED** [review]

**Review by MCele — CHANGES_REQUESTED** [review]
Si al momento de realizar el cambio de cama, se modifican las fechas realiza bien los controles. Pero si esto no ocurre y se usa la fecha actual del mapa, ya se pierden algunos controles. 
Puntualmente para eso sigo visualizando pacientes duplicados en el mapa de camas.
image
Dejo los pasos para reproducir el error. Tener 2 pantallas sobre el mapa de camas (simulando 2 usuarios). Cada mapa se deben cargar en fechas y horarios fijos antes de continuar. Luego, realizo las siguientes acciones en cada pantalla (sin actualizar fecha del mapa):
pantalla 1: paciente es movido a la cama "cama 1" fecha 11:40
pantalla 2: paciente es movido a la cama "cama_campe_2" a as 11:44

Sugerencia: quizás al momento de guardar finalmente un movimiento, se puede controlar si se parte del último movimiento para dicha internación, si no es así, simplemente que no se permita guardarlo.

**Review by MCele — APPROVED** [review]

**Pull request merged**
