### PR TITLE
Core - Actualizacion plex

### PR DESCRIPTION
**Pull request by martinebucarey**
### Requerimiento
Actualizar plex a la ultima version.

### Funcionalidad desarrollada 

1. Se actualiza plex a la version 7.23
2. EN caso de error en las dependencias, correr con npm i --legacy-peer-deps

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [x] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [x] Si https://github.com/andes/andes-test-integracion/pull/447
- [ ] No

### CODE REVIEW

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [6796](http://condorpiedra.andes.gob.ar:85/6796/mochawesome.html)
CYPRESS RUN: [5647](https://dashboard.cypress.io/projects/xr7gft/runs/5647/specs)
TEST START: 2022-07-06T12:46:57.876Z
TOTAL: 409
SUCCESS: 406
FAIL: 1
SKIPPED: 2

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [6797](http://condorpiedra.andes.gob.ar:85/6797/mochawesome.html)
CYPRESS RUN: [5648](https://dashboard.cypress.io/projects/xr7gft/runs/5648/specs)
TEST START: 2022-07-06T12:57:39.251Z
TOTAL: 351
SUCCESS: 337
FAIL: 13
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [6804](http://condorpiedra.andes.gob.ar:85/6804/mochawesome.html)
CYPRESS RUN: [5655](https://dashboard.cypress.io/projects/xr7gft/runs/5655/specs)
TEST START: 2022-07-06T18:40:52.112Z
TOTAL: 409
SUCCESS: 403
FAIL: 4
SKIPPED: 2

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [6811](http://condorpiedra.andes.gob.ar:85/6811/mochawesome.html)
CYPRESS RUN: [5661](https://dashboard.cypress.io/projects/xr7gft/runs/5661/specs)
TEST START: 2022-07-07T13:38:11.061Z
TOTAL: 409
SUCCESS: 403
FAIL: 4
SKIPPED: 2

**Review by palita1991 — APPROVED** [review]
El único detalle encontrado es lo del badge de profesional en el gestor de usuarios que se soluciona con este PR  de plex https://github.com/andes/plex/pull/321

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [6894](http://condorpiedra.andes.gob.ar:85/6894/mochawesome.html)
CYPRESS RUN: [5738](https://dashboard.cypress.io/projects/xr7gft/runs/5738/specs)
TEST START: 2022-07-13T15:04:32.194Z
TOTAL: 385
SUCCESS: 376
FAIL: 8
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [6917](http://condorpiedra.andes.gob.ar:85/6917/mochawesome.html)
CYPRESS RUN: [5761](https://dashboard.cypress.io/projects/xr7gft/runs/5761/specs)
TEST START: 2022-07-14T16:37:58.531Z
TOTAL: 409
SUCCESS: 404
FAIL: 4
SKIPPED: 1

**Review by plammel — APPROVED** [review]

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7195](http://condorpiedra.andes.gob.ar:85/7195/mochawesome.html)
CYPRESS RUN: [5971](https://dashboard.cypress.io/projects/xr7gft/runs/5971/specs)
TEST START: 2022-07-28T18:08:32.573Z
TOTAL: 408
SUCCESS: 406
FAIL: 1
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7197](http://condorpiedra.andes.gob.ar:85/7197/mochawesome.html)
CYPRESS RUN: [5972](https://dashboard.cypress.io/projects/xr7gft/runs/5972/specs)
TEST START: 2022-07-28T18:18:01.356Z
TOTAL: 334
SUCCESS: 326
FAIL: 7
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7232](http://condorpiedra.andes.gob.ar:85/7232/mochawesome.html)
CYPRESS RUN: [5990](https://dashboard.cypress.io/projects/xr7gft/runs/5990/specs)
TEST START: 2022-07-29T18:05:25.239Z
TOTAL: 408
SUCCESS: 404
FAIL: 3
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7233](http://condorpiedra.andes.gob.ar:85/7233/mochawesome.html)
CYPRESS RUN: [5991](https://dashboard.cypress.io/projects/xr7gft/runs/5991/specs)
TEST START: 2022-07-29T18:16:01.134Z
TOTAL: 408
SUCCESS: 406
FAIL: 1
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7234](http://condorpiedra.andes.gob.ar:85/7234/mochawesome.html)
CYPRESS RUN: [5992](https://dashboard.cypress.io/projects/xr7gft/runs/5992/specs)
TEST START: 2022-07-29T18:52:10.492Z
TOTAL: 408
SUCCESS: 399
FAIL: 8
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7265](http://condorpiedra.andes.gob.ar:85/7265/mochawesome.html)
CYPRESS RUN: [6023](https://dashboard.cypress.io/projects/xr7gft/runs/6023/specs)
TEST START: 2022-08-02T11:34:07.633Z
TOTAL: 408
SUCCESS: 406
FAIL: 1
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7272](http://condorpiedra.andes.gob.ar:85/7272/mochawesome.html)
CYPRESS RUN: [6030](https://dashboard.cypress.io/projects/xr7gft/runs/6030/specs)
TEST START: 2022-08-02T13:51:08.523Z
TOTAL: 408
SUCCESS: 406
FAIL: 1
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7273](http://condorpiedra.andes.gob.ar:85/7273/mochawesome.html)
CYPRESS RUN: [6031](https://dashboard.cypress.io/projects/xr7gft/runs/6031/specs)
TEST START: 2022-08-02T14:00:31.153Z
TOTAL: 365
SUCCESS: 357
FAIL: 7
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7274](http://condorpiedra.andes.gob.ar:85/7274/mochawesome.html)
CYPRESS RUN: [6032](https://dashboard.cypress.io/projects/xr7gft/runs/6032/specs)
TEST START: 2022-08-02T14:11:25.876Z
TOTAL: 408
SUCCESS: 407
FAIL: 0
SKIPPED: 1

**Pull request merged**
