### PR TITLE
style(IN): se cambian labels por mas descriptivos

### PR DESCRIPTION
**Pull request by leon-bravo**
### Requerimiento
 
[IN-413](https://proyectos.andes.gob.ar/browse/IN-413) - Egreso de una internacion: Modificar label
### Funcionalidad desarrollada 

1. Se modifican los labels de "Otras circunstancias" por "Otras circunstancias que prolongan la internación" y "Otro diagnostico" por "Otros diagnósticos"
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [X] Si
- [ ] No

https://github.com/andes/andes-test-integracion/pull/431

### CODE REVIEW

**Comment by martinebucarey** [comment]
USUARIO: lbravo  
BUILD NUMBER: [6407](http://condorpiedra.andes.gob.ar:85/6407/mochawesome.html)
CYPRESS RUN: [5290](https://dashboard.cypress.io/projects/xr7gft/runs/5290/specs)
TEST START: 2022-05-11T13:13:07.375Z
TOTAL: 406
SUCCESS: 402
FAIL: 3
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: lbravo  
BUILD NUMBER: [6409](http://condorpiedra.andes.gob.ar:85/6409/mochawesome.html)
CYPRESS RUN: [5291](https://dashboard.cypress.io/projects/xr7gft/runs/5291/specs)
TEST START: 2022-05-11T13:38:37.052Z
TOTAL: 406
SUCCESS: 401
FAIL: 4
SKIPPED: 1

**Review by martinebucarey — APPROVED** [review]

**Review by AgosLizzi — APPROVED** [review]

**Comment by martinebucarey** [comment]
USUARIO: plammel  
BUILD NUMBER: [6438](http://condorpiedra.andes.gob.ar:85/6438/mochawesome.html)
CYPRESS RUN: [5320](https://dashboard.cypress.io/projects/xr7gft/runs/5320/specs)
TEST START: 2022-05-16T17:21:13.284Z
TOTAL: 406
SUCCESS: 401
FAIL: 4
SKIPPED: 1

**Review by plammel — DISMISSED** [review]
@leon-bravo fijate que hay que hacer modificaciones en los test de internación

**Comment by martinebucarey** [comment]
USUARIO: plammel  
BUILD NUMBER: [6439](http://condorpiedra.andes.gob.ar:85/6439/mochawesome.html)
CYPRESS RUN: [5321](https://dashboard.cypress.io/projects/xr7gft/runs/5321/specs)
TEST START: 2022-05-16T17:44:44.917Z
TOTAL: 406
SUCCESS: 400
FAIL: 5
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: lbravo  
BUILD NUMBER: [6443](http://condorpiedra.andes.gob.ar:85/6443/mochawesome.html)
CYPRESS RUN: [5325](https://dashboard.cypress.io/projects/xr7gft/runs/5325/specs)
TEST START: 2022-05-16T19:12:50.496Z
TOTAL: 398
SUCCESS: 392
FAIL: 5
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: lbravo  
BUILD NUMBER: [6445](http://condorpiedra.andes.gob.ar:85/6445/mochawesome.html)
CYPRESS RUN: [5327](https://dashboard.cypress.io/projects/xr7gft/runs/5327/specs)
TEST START: 2022-05-16T21:15:52.129Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: lbravo  
BUILD NUMBER: [6450](http://condorpiedra.andes.gob.ar:85/6450/mochawesome.html)
CYPRESS RUN: [5332](https://dashboard.cypress.io/projects/xr7gft/runs/5332/specs)
TEST START: 2022-05-17T12:14:45.819Z
TOTAL: 406
SUCCESS: 402
FAIL: 3
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: lbravo  
BUILD NUMBER: [6459](http://condorpiedra.andes.gob.ar:85/6459/mochawesome.html)
CYPRESS RUN: [5341](https://dashboard.cypress.io/projects/xr7gft/runs/5341/specs)
TEST START: 2022-05-17T15:46:48.375Z
TOTAL: 398
SUCCESS: 396
FAIL: 1
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: lbravo  
BUILD NUMBER: [6460](http://condorpiedra.andes.gob.ar:85/6460/mochawesome.html)
CYPRESS RUN: [5342](https://dashboard.cypress.io/projects/xr7gft/runs/5342/specs)
TEST START: 2022-05-17T15:56:04.863Z
TOTAL: 406
SUCCESS: 388
FAIL: 17
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: lbravo  
BUILD NUMBER: [6465](http://condorpiedra.andes.gob.ar:85/6465/mochawesome.html)
CYPRESS RUN: [5347](https://dashboard.cypress.io/projects/xr7gft/runs/5347/specs)
TEST START: 2022-05-19T12:37:40.761Z
TOTAL: 398
SUCCESS: 396
FAIL: 1
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [6471](http://condorpiedra.andes.gob.ar:85/6471/mochawesome.html)
CYPRESS RUN: [5353](https://dashboard.cypress.io/projects/xr7gft/runs/5353/specs)
TEST START: 2022-05-19T14:48:12.993Z
TOTAL: 406
SUCCESS: 393
FAIL: 12
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: lbravo  
BUILD NUMBER: [6472](http://condorpiedra.andes.gob.ar:85/6472/mochawesome.html)
CYPRESS RUN: [5354](https://dashboard.cypress.io/projects/xr7gft/runs/5354/specs)
TEST START: 2022-05-19T16:15:22.148Z
TOTAL: 381
SUCCESS: 373
FAIL: 7
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: lbravo  
BUILD NUMBER: [6479](http://condorpiedra.andes.gob.ar:85/6479/mochawesome.html)
CYPRESS RUN: [5360](https://dashboard.cypress.io/projects/xr7gft/runs/5360/specs)
TEST START: 2022-05-19T19:15:56.518Z
TOTAL: 356
SUCCESS: 344
FAIL: 12
SKIPPED: 0

**Comment by martinebucarey** [comment]
USUARIO: lbravo  
BUILD NUMBER: [6480](http://condorpiedra.andes.gob.ar:85/6480/mochawesome.html)
CYPRESS RUN: [5361](https://dashboard.cypress.io/projects/xr7gft/runs/5361/specs)
TEST START: 2022-05-19T19:28:48.286Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

**Pull request merged**
