### PR TITLE
IN - Capa medica, nuevo registro no precarga fecha y hora

### PR DESCRIPTION
**Pull request by negro89**
### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-441

### Funcionalidad desarrollada 

1. Se inicializan fecha y hora para un nuevo registro de internación

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [X] Si https://github.com/andes/andes-test-integracion/pull/434
- [ ] No

### CODE REVIEW

**Comment by martinebucarey** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [6490](http://condorpiedra.andes.gob.ar:85/6490/mochawesome.html)
CYPRESS RUN: [5371](https://dashboard.cypress.io/projects/xr7gft/runs/5371/specs)
TEST START: 2022-05-24T17:24:18.062Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [6491](http://condorpiedra.andes.gob.ar:85/6491/mochawesome.html)
CYPRESS RUN: [5372](https://dashboard.cypress.io/projects/xr7gft/runs/5372/specs)
TEST START: 2022-05-24T17:42:02.613Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [6492](http://condorpiedra.andes.gob.ar:85/6492/mochawesome.html)
CYPRESS RUN: [5373](https://dashboard.cypress.io/projects/xr7gft/runs/5373/specs)
TEST START: 2022-05-24T18:20:27.968Z
TOTAL: 402
SUCCESS: 400
FAIL: 1
SKIPPED: 1

**Review by palita1991 — APPROVED** [review]

**Comment by martinebucarey** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [6531](http://condorpiedra.andes.gob.ar:85/6531/mochawesome.html)
CYPRESS RUN: [5412](https://dashboard.cypress.io/projects/xr7gft/runs/5412/specs)
TEST START: 2022-06-01T11:55:19.750Z
TOTAL: 346
SUCCESS: 332
FAIL: 13
SKIPPED: 1

**Review by MCele — APPROVED** [review]

**Comment by martinebucarey** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [6532](http://condorpiedra.andes.gob.ar:85/6532/mochawesome.html)
CYPRESS RUN: [5413](https://dashboard.cypress.io/projects/xr7gft/runs/5413/specs)
TEST START: 2022-06-01T13:51:26.936Z
TOTAL: 406
SUCCESS: 381
FAIL: 24
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [6534](http://condorpiedra.andes.gob.ar:85/6534/mochawesome.html)
CYPRESS RUN: [5415](https://dashboard.cypress.io/projects/xr7gft/runs/5415/specs)
TEST START: 2022-06-01T14:32:26.800Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: cramos  
BUILD NUMBER: [6540](http://condorpiedra.andes.gob.ar:85/6540/mochawesome.html)
CYPRESS RUN: [5420](https://dashboard.cypress.io/projects/xr7gft/runs/5420/specs)
TEST START: 2022-06-01T15:54:44.470Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

**Pull request merged**
