### PR TITLE
TM: limpieza service profesionales

### PR DESCRIPTION
**Pull request by plammel**
### Requerimiento
 
https://proyectos.andes.gob.ar/browse/TM-23
### Funcionalidad desarrollada 

1. limpieza service profesionales
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

### CODE REVIEW

**Review by palita1991 — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8376](http://condorpiedra.andes.gob.ar:85/8376/mochawesome.html)
CYPRESS RUN: [7553](https://dashboard.cypress.io/projects/xr7gft/runs/7553/specs)
TEST START: 2023-02-08T13:41:17.909Z
TOTAL: 406
SUCCESS: 397
FAIL: 7
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8377](http://condorpiedra.andes.gob.ar:85/8377/mochawesome.html)
CYPRESS RUN: [7554](https://dashboard.cypress.io/projects/xr7gft/runs/7554/specs)
TEST START: 2023-02-08T13:51:52.373Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8378](http://condorpiedra.andes.gob.ar:85/8378/mochawesome.html)
CYPRESS RUN: [7555](https://dashboard.cypress.io/projects/xr7gft/runs/7555/specs)
TEST START: 2023-02-08T14:15:24.572Z
TOTAL: 385
SUCCESS: 376
FAIL: 7
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8379](http://condorpiedra.andes.gob.ar:85/8379/mochawesome.html)
CYPRESS RUN: [7556](https://dashboard.cypress.io/projects/xr7gft/runs/7556/specs)
TEST START: 2023-02-08T14:42:25.713Z
TOTAL: 406
SUCCESS: 390
FAIL: 14
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8381](http://condorpiedra.andes.gob.ar:85/8381/mochawesome.html)
CYPRESS RUN: [7558](https://dashboard.cypress.io/projects/xr7gft/runs/7558/specs)
TEST START: 2023-02-08T15:36:01.919Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

**Review by negro89 — APPROVED** [review]

**Pull request merged**
