### PR TITLE
feat(elementos-rup): add rules

### PR DESCRIPTION
**Pull request by liquid36**
### Requerimiento
Agrega reglas dinamicas en Elementos RUP para validar, e interactuar entre elementos. 
 
### UserStory llegó a completarse 
- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos 
- [ ] Si
- [ ] No

### Requiere actualizaciones en la API 
- [ ] Si https://github.com/andes/api/pull/1209
- [ ] No

### Requiere actualizaciones en andes-test-integracion 
- [ ] Si
- [ ] No

### CODE REVIEW

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2762](http://condorpiedra.andes.gob.ar:85/2762/mochawesome.html)
CYPRESS RUN: [1904](https://dashboard.cypress.io/projects/xr7gft/runs/1904/specs)
TEST START: 2020-11-26T13:26:18.034Z
TOTAL: 350
SUCCESS: 349
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2763](http://condorpiedra.andes.gob.ar:85/2763/mochawesome.html)
CYPRESS RUN: [1905](https://dashboard.cypress.io/projects/xr7gft/runs/1905/specs)
TEST START: 2020-11-26T13:40:13.649Z
TOTAL: 350
SUCCESS: 350
FAIL: 0
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2767](http://condorpiedra.andes.gob.ar:85/2767/mochawesome.html)
CYPRESS RUN: [1909](https://dashboard.cypress.io/projects/xr7gft/runs/1909/specs)
TEST START: 2020-11-26T15:10:30.068Z
TOTAL: 333
SUCCESS: 331
FAIL: 2
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2769](http://condorpiedra.andes.gob.ar:85/2769/mochawesome.html)
CYPRESS RUN: [1911](https://dashboard.cypress.io/projects/xr7gft/runs/1911/specs)
TEST START: 2020-11-26T15:30:16.687Z
TOTAL: 351
SUCCESS: 351
FAIL: 0
SKIPPED: 0

**Review by palita1991 — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2786](http://condorpiedra.andes.gob.ar:85/2786/mochawesome.html)
CYPRESS RUN: [1928](https://dashboard.cypress.io/projects/xr7gft/runs/1928/specs)
TEST START: 2020-11-30T15:16:39.167Z
TOTAL: 354
SUCCESS: 354
FAIL: 0
SKIPPED: 0

**Pull request merged**
