### PR TITLE
MPI: corrige error que cruza pacientes por scan

### PR DESCRIPTION
**Pull request by MCele**
### Requerimiento
 
corrige error donde se mezclan pacientes luego de usar scan
https://proyectos.andes.gob.ar/browse/MPI-419
https://glpi.andes.gob.ar/front/ticket.form.php?id=4380

### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [9977](http://condorpiedra.andes.gob.ar:85/9977/mochawesome.html)
CYPRESS RUN: [9088](https://dashboard.cypress.io/projects/xr7gft/runs/9088/specs)
TEST START: 2023-11-27T15:08:37.670Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [9997](http://condorpiedra.andes.gob.ar:85/9997/mochawesome.html)
CYPRESS RUN: [9106](https://dashboard.cypress.io/projects/xr7gft/runs/9106/specs)
TEST START: 2023-11-29T12:38:23.602Z
TOTAL: 375
SUCCESS: 368
FAIL: 5
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [9998](http://condorpiedra.andes.gob.ar:85/9998/mochawesome.html)
CYPRESS RUN: [9107](https://dashboard.cypress.io/projects/xr7gft/runs/9107/specs)
TEST START: 2023-11-29T13:03:54.875Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Review by negro89 — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [10007](http://condorpiedra.andes.gob.ar:85/10007/mochawesome.html)
CYPRESS RUN: [9116](https://dashboard.cypress.io/projects/xr7gft/runs/9116/specs)
TEST START: 2023-12-01T14:38:55.641Z
TOTAL: 95
SUCCESS: 0
FAIL: 95
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [10022](http://condorpiedra.andes.gob.ar:85/10022/mochawesome.html)
CYPRESS RUN: [9131](https://dashboard.cypress.io/projects/xr7gft/runs/9131/specs)
TEST START: 2023-12-04T14:33:09.977Z
TOTAL: 384
SUCCESS: 377
FAIL: 5
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [10024](http://condorpiedra.andes.gob.ar:85/10024/mochawesome.html)
CYPRESS RUN: [9133](https://dashboard.cypress.io/projects/xr7gft/runs/9133/specs)
TEST START: 2023-12-04T14:59:44.048Z
TOTAL: 396
SUCCESS: 388
FAIL: 6
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [10025](http://condorpiedra.andes.gob.ar:85/10025/mochawesome.html)
CYPRESS RUN: [9134](https://dashboard.cypress.io/projects/xr7gft/runs/9134/specs)
TEST START: 2023-12-04T15:19:04.360Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Pull request merged**
