### PR TITLE
EP: refactor de historial de ficha

### PR DESCRIPTION
**Pull request by plammel**
### Requerimiento
 
Se remueve el save de historial de fichas del lado de la app, para delegarlo a la api
### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [x] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1491
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [x] Si https://github.com/andes/andes-test-integracion/pull/382
- [x] No

### CODE REVIEW

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [4711](http://condorpiedra.andes.gob.ar:85/4711/mochawesome.html)
CYPRESS RUN: [3710](https://dashboard.cypress.io/projects/xr7gft/runs/3710/specs)
TEST START: 2021-07-26T18:39:45.686Z
TOTAL: 375
SUCCESS: 362
FAIL: 12
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [4727](http://condorpiedra.andes.gob.ar:85/4727/mochawesome.html)
CYPRESS RUN: [3724](https://dashboard.cypress.io/projects/xr7gft/runs/3724/specs)
TEST START: 2021-07-27T14:13:09.038Z
TOTAL: 392
SUCCESS: 389
FAIL: 2
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [4733](http://condorpiedra.andes.gob.ar:85/4733/mochawesome.html)
CYPRESS RUN: [3730](https://dashboard.cypress.io/projects/xr7gft/runs/3730/specs)
TEST START: 2021-07-27T18:12:58.300Z
TOTAL: 382
SUCCESS: 378
FAIL: 3
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [4738](http://condorpiedra.andes.gob.ar:85/4738/mochawesome.html)
CYPRESS RUN: [3735](https://dashboard.cypress.io/projects/xr7gft/runs/3735/specs)
TEST START: 2021-07-28T12:15:21.064Z
TOTAL: 400
SUCCESS: 397
FAIL: 2
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [4757](http://condorpiedra.andes.gob.ar:85/4757/mochawesome.html)
CYPRESS RUN: [3753](https://dashboard.cypress.io/projects/xr7gft/runs/3753/specs)
TEST START: 2021-07-29T15:54:20.221Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [4781](http://condorpiedra.andes.gob.ar:85/4781/mochawesome.html)
CYPRESS RUN: [3777](https://dashboard.cypress.io/projects/xr7gft/runs/3777/specs)
TEST START: 2021-08-03T15:03:27.401Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [4786](http://condorpiedra.andes.gob.ar:85/4786/mochawesome.html)
CYPRESS RUN: [3782](https://dashboard.cypress.io/projects/xr7gft/runs/3782/specs)
TEST START: 2021-08-03T16:16:17.221Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [4788](http://condorpiedra.andes.gob.ar:85/4788/mochawesome.html)
CYPRESS RUN: [3784](https://dashboard.cypress.io/projects/xr7gft/runs/3784/specs)
TEST START: 2021-08-03T16:57:30.792Z
TOTAL: 334
SUCCESS: 317
FAIL: 16
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [4792](http://condorpiedra.andes.gob.ar:85/4792/mochawesome.html)
CYPRESS RUN: [3787](https://dashboard.cypress.io/projects/xr7gft/runs/3787/specs)
TEST START: 2021-08-03T18:07:01.223Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

**Review by martinebucarey — APPROVED** [review]

**Review by liquid36 — APPROVED** [review]

**Pull request merged**
