### PR TITLE
feat(chore): activa ivy

### PR DESCRIPTION
**Pull request by liquid36**
### Requerimiento

Mágicamente se acomodaron los astro y funciona la compilación con IVY. Después de esto podemos actualizar a Angular 11.

### UserStory llegó a completarse
- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [x] No

### Requiere actualizaciones en la API
- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion
- [ ] Si
- [x] No

### CODE REVIEW

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2901](http://condorpiedra.andes.gob.ar:85/2901/mochawesome.html)
CYPRESS RUN: [2035](https://dashboard.cypress.io/projects/xr7gft/runs/2035/specs)
TEST START: 2020-12-16T18:27:27.988Z
TOTAL: 350
SUCCESS: 334
FAIL: 16
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2902](http://condorpiedra.andes.gob.ar:85/2902/mochawesome.html)
CYPRESS RUN: [2036](https://dashboard.cypress.io/projects/xr7gft/runs/2036/specs)
TEST START: 2020-12-16T18:35:39.316Z
TOTAL: 344
SUCCESS: 329
FAIL: 15
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2910](http://condorpiedra.andes.gob.ar:85/2910/mochawesome.html)
CYPRESS RUN: [2044](https://dashboard.cypress.io/projects/xr7gft/runs/2044/specs)
TEST START: 2020-12-17T11:40:36.040Z
TOTAL: 350
SUCCESS: 338
FAIL: 12
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2913](http://condorpiedra.andes.gob.ar:85/2913/mochawesome.html)
CYPRESS RUN: [2046](https://dashboard.cypress.io/projects/xr7gft/runs/2046/specs)
TEST START: 2020-12-17T13:06:24.468Z
TOTAL: 350
SUCCESS: 345
FAIL: 5
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2914](http://condorpiedra.andes.gob.ar:85/2914/mochawesome.html)
CYPRESS RUN: [2047](https://dashboard.cypress.io/projects/xr7gft/runs/2047/specs)
TEST START: 2020-12-17T13:20:27.509Z
TOTAL: 350
SUCCESS: 343
FAIL: 7
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2915](http://condorpiedra.andes.gob.ar:85/2915/mochawesome.html)
CYPRESS RUN: [2048](https://dashboard.cypress.io/projects/xr7gft/runs/2048/specs)
TEST START: 2020-12-17T13:31:21.221Z
TOTAL: 350
SUCCESS: 345
FAIL: 5
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2916](http://condorpiedra.andes.gob.ar:85/2916/mochawesome.html)
CYPRESS RUN: [2049](https://dashboard.cypress.io/projects/xr7gft/runs/2049/specs)
TEST START: 2020-12-17T13:33:34.483Z
TOTAL: 2
SUCCESS: 0
FAIL: 2
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2917](http://condorpiedra.andes.gob.ar:85/2917/mochawesome.html)
CYPRESS RUN: [2050](https://dashboard.cypress.io/projects/xr7gft/runs/2050/specs)
TEST START: 2020-12-17T13:41:48.473Z
TOTAL: 2
SUCCESS: 0
FAIL: 2
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2919](http://condorpiedra.andes.gob.ar:85/2919/mochawesome.html)
CYPRESS RUN: [2052](https://dashboard.cypress.io/projects/xr7gft/runs/2052/specs)
TEST START: 2020-12-17T14:23:21.127Z
TOTAL: 355
SUCCESS: 347
FAIL: 8
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2921](http://condorpiedra.andes.gob.ar:85/2921/mochawesome.html)
CYPRESS RUN: [2054](https://dashboard.cypress.io/projects/xr7gft/runs/2054/specs)
TEST START: 2020-12-17T14:40:46.692Z
TOTAL: 2
SUCCESS: 0
FAIL: 2
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2922](http://condorpiedra.andes.gob.ar:85/2922/mochawesome.html)
CYPRESS RUN: [2055](https://dashboard.cypress.io/projects/xr7gft/runs/2055/specs)
TEST START: 2020-12-17T14:56:17.335Z
TOTAL: 2
SUCCESS: 0
FAIL: 2
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2926](http://condorpiedra.andes.gob.ar:85/2926/mochawesome.html)
CYPRESS RUN: [2059](https://dashboard.cypress.io/projects/xr7gft/runs/2059/specs)
TEST START: 2020-12-17T15:30:46.429Z
TOTAL: 337
SUCCESS: 332
FAIL: 5
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2929](http://condorpiedra.andes.gob.ar:85/2929/mochawesome.html)
CYPRESS RUN: [2062](https://dashboard.cypress.io/projects/xr7gft/runs/2062/specs)
TEST START: 2020-12-17T16:27:17.127Z
TOTAL: 355
SUCCESS: 353
FAIL: 2
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2930](http://condorpiedra.andes.gob.ar:85/2930/mochawesome.html)
CYPRESS RUN: [2063](https://dashboard.cypress.io/projects/xr7gft/runs/2063/specs)
TEST START: 2020-12-17T16:51:59.676Z
TOTAL: 355
SUCCESS: 355
FAIL: 0
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [2995](http://condorpiedra.andes.gob.ar:85/2995/mochawesome.html)
CYPRESS RUN: [2124](https://dashboard.cypress.io/projects/xr7gft/runs/2124/specs)
TEST START: 2021-01-04T13:55:06.417Z
TOTAL: 353
SUCCESS: 350
FAIL: 3
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [2996](http://condorpiedra.andes.gob.ar:85/2996/mochawesome.html)
CYPRESS RUN: [2125](https://dashboard.cypress.io/projects/xr7gft/runs/2125/specs)
TEST START: 2021-01-04T14:59:58.128Z
TOTAL: 13
SUCCESS: 11
FAIL: 2
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [2997](http://condorpiedra.andes.gob.ar:85/2997/mochawesome.html)
CYPRESS RUN: [2126](https://dashboard.cypress.io/projects/xr7gft/runs/2126/specs)
TEST START: 2021-01-04T15:33:07.701Z
TOTAL: 353
SUCCESS: 353
FAIL: 0
SKIPPED: 0

**Review by palita1991 — APPROVED** [review]

**Pull request merged**
