### PR TITLE
Migrar iconos a andes-font

### PR DESCRIPTION
**Pull request by AgosLizzi**
https://proyectos.andes.gob.ar/browse/PLEX-324
### Requerimiento
Actualmente se utiliza la librería de iconos de andes-font y de material design , se modificaron algun de los iconos provenientes de la dependecia de material design.
### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [X] Si, https://github.com/andes/andes-test-integracion/pull/495
- [ ] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: alizzi  
BUILD NUMBER: [9302](http://condorpiedra.andes.gob.ar:85/9302/mochawesome.html)
CYPRESS RUN: [8447](https://dashboard.cypress.io/projects/xr7gft/runs/8447/specs)
TEST START: 2023-07-28T12:49:14.932Z
TOTAL: 403
SUCCESS: 390
FAIL: 11
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [9303](http://condorpiedra.andes.gob.ar:85/9303/mochawesome.html)
CYPRESS RUN: [8448](https://dashboard.cypress.io/projects/xr7gft/runs/8448/specs)
TEST START: 2023-07-28T13:41:23.358Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [9304](http://condorpiedra.andes.gob.ar:85/9304/mochawesome.html)
CYPRESS RUN: [8449](https://dashboard.cypress.io/projects/xr7gft/runs/8449/specs)
TEST START: 2023-07-28T13:59:21.461Z
TOTAL: 403
SUCCESS: 397
FAIL: 4
SKIPPED: 2

**Review by MarianoCampetella — APPROVED** [review]

**Review by MCele — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [9783](http://condorpiedra.andes.gob.ar:85/9783/mochawesome.html)
CYPRESS RUN: [8893](https://dashboard.cypress.io/projects/xr7gft/runs/8893/specs)
TEST START: 2023-10-18T18:17:14.732Z
TOTAL: 385
SUCCESS: 375
FAIL: 8
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [9784](http://condorpiedra.andes.gob.ar:85/9784/mochawesome.html)
CYPRESS RUN: [8894](https://dashboard.cypress.io/projects/xr7gft/runs/8894/specs)
TEST START: 2023-10-18T18:32:41.444Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [9785](http://condorpiedra.andes.gob.ar:85/9785/mochawesome.html)
CYPRESS RUN: [8895](https://dashboard.cypress.io/projects/xr7gft/runs/8895/specs)
TEST START: 2023-10-18T19:10:49.148Z
TOTAL: 310
SUCCESS: 292
FAIL: 16
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [9787](http://condorpiedra.andes.gob.ar:85/9787/mochawesome.html)
CYPRESS RUN: [8897](https://dashboard.cypress.io/projects/xr7gft/runs/8897/specs)
TEST START: 2023-10-19T18:23:54.269Z
TOTAL: 95
SUCCESS: 0
FAIL: 95
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [9798](http://condorpiedra.andes.gob.ar:85/9798/mochawesome.html)
CYPRESS RUN: [8908](https://dashboard.cypress.io/projects/xr7gft/runs/8908/specs)
TEST START: 2023-10-20T20:43:51.015Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [9799](http://condorpiedra.andes.gob.ar:85/9799/mochawesome.html)
CYPRESS RUN: [8909](https://dashboard.cypress.io/projects/xr7gft/runs/8909/specs)
TEST START: 2023-10-20T21:19:13.947Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [9800](http://condorpiedra.andes.gob.ar:85/9800/mochawesome.html)
CYPRESS RUN: [8910](https://dashboard.cypress.io/projects/xr7gft/runs/8910/specs)
TEST START: 2023-10-20T21:48:44.433Z
TOTAL: 356
SUCCESS: 343
FAIL: 12
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [9804](http://condorpiedra.andes.gob.ar:85/9804/mochawesome.html)
CYPRESS RUN: [8914](https://dashboard.cypress.io/projects/xr7gft/runs/8914/specs)
TEST START: 2023-10-23T19:44:12.946Z
TOTAL: 282
SUCCESS: 264
FAIL: 16
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [9805](http://condorpiedra.andes.gob.ar:85/9805/mochawesome.html)
CYPRESS RUN: [8915](https://dashboard.cypress.io/projects/xr7gft/runs/8915/specs)
TEST START: 2023-10-23T20:04:19.163Z
TOTAL: 308
SUCCESS: 280
FAIL: 26
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [9817](http://condorpiedra.andes.gob.ar:85/9817/mochawesome.html)
CYPRESS RUN: [8927](https://dashboard.cypress.io/projects/xr7gft/runs/8927/specs)
TEST START: 2023-10-25T16:53:47.780Z
TOTAL: 394
SUCCESS: 390
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [9818](http://condorpiedra.andes.gob.ar:85/9818/mochawesome.html)
CYPRESS RUN: [8928](https://dashboard.cypress.io/projects/xr7gft/runs/8928/specs)
TEST START: 2023-10-25T17:10:46.060Z
TOTAL: 335
SUCCESS: 331
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [9821](http://condorpiedra.andes.gob.ar:85/9821/mochawesome.html)
CYPRESS RUN: [8931](https://dashboard.cypress.io/projects/xr7gft/runs/8931/specs)
TEST START: 2023-10-25T19:24:10.805Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Pull request merged**
