### PR TITLE
MISC - Mejoras en el buscador de turnos y prestaciones

### PR DESCRIPTION
**Pull request by MarianoCampetella**
### Requerimiento
https://proyectos.andes.gob.ar/browse/MISC-132

### Funcionalidad desarrollada 
1. Se agregaron tooltips en los botones "exportar" y "descargas pendientes".
2. Al momento de exportar uno o varios elementos del listado se abre automáticamente el sidebar de descargas pendientes para evitar realizar varios clicks.

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [X] Si   https://github.com/andes/andes-test-integracion/pull/412
- [ ] No

### CODE REVIEW

**Comment by liquid36** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [5862](http://condorpiedra.andes.gob.ar:85/5862/mochawesome.html)
CYPRESS RUN: [4780](https://dashboard.cypress.io/projects/xr7gft/runs/4780/specs)
TEST START: 2022-01-27T18:18:18.893Z
TOTAL: 404
SUCCESS: 401
FAIL: 2
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [5863](http://condorpiedra.andes.gob.ar:85/5863/mochawesome.html)
CYPRESS RUN: [4781](https://dashboard.cypress.io/projects/xr7gft/runs/4781/specs)
TEST START: 2022-01-27T18:36:34.051Z
TOTAL: 343
SUCCESS: 328
FAIL: 14
SKIPPED: 1

**Review by martinebucarey — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [5865](http://condorpiedra.andes.gob.ar:85/5865/mochawesome.html)
CYPRESS RUN: [4783](https://dashboard.cypress.io/projects/xr7gft/runs/4783/specs)
TEST START: 2022-01-28T11:28:34.015Z
TOTAL: 404
SUCCESS: 401
FAIL: 2
SKIPPED: 1

**Review by AgosLizzi — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [5872](http://condorpiedra.andes.gob.ar:85/5872/mochawesome.html)
CYPRESS RUN: [4790](https://dashboard.cypress.io/projects/xr7gft/runs/4790/specs)
TEST START: 2022-01-31T16:46:19.964Z
TOTAL: 404
SUCCESS: 401
FAIL: 2
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [5873](http://condorpiedra.andes.gob.ar:85/5873/mochawesome.html)
CYPRESS RUN: [4791](https://dashboard.cypress.io/projects/xr7gft/runs/4791/specs)
TEST START: 2022-01-31T19:32:51.981Z
TOTAL: 351
SUCCESS: 338
FAIL: 12
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [5875](http://condorpiedra.andes.gob.ar:85/5875/mochawesome.html)
CYPRESS RUN: [4793](https://dashboard.cypress.io/projects/xr7gft/runs/4793/specs)
TEST START: 2022-02-01T11:45:17.198Z
TOTAL: 404
SUCCESS: 393
FAIL: 10
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [5876](http://condorpiedra.andes.gob.ar:85/5876/mochawesome.html)
CYPRESS RUN: [4794](https://dashboard.cypress.io/projects/xr7gft/runs/4794/specs)
TEST START: 2022-02-01T11:55:03.542Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [5877](http://condorpiedra.andes.gob.ar:85/5877/mochawesome.html)
CYPRESS RUN: [4795](https://dashboard.cypress.io/projects/xr7gft/runs/4795/specs)
TEST START: 2022-02-01T12:05:09.067Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

**Review by waltergarrido — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [5880](http://condorpiedra.andes.gob.ar:85/5880/mochawesome.html)
CYPRESS RUN: [4798](https://dashboard.cypress.io/projects/xr7gft/runs/4798/specs)
TEST START: 2022-02-01T13:21:38.207Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

**Pull request merged**
