### PR TITLE
IN - Fecha y hora del mapa de camas

### PR DESCRIPTION
**Pull request by MarianoCampetella**
### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-569

### Funcionalidad desarrollada 
1. Se agrego un botón con la función de editar la fecha del mapa de camas.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [X] Si   https://github.com/andes/andes-test-integracion/pull/500
- [ ] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [9863](http://condorpiedra.andes.gob.ar:85/9863/mochawesome.html)
CYPRESS RUN: [8970](https://dashboard.cypress.io/projects/xr7gft/runs/8970/specs)
TEST START: 2023-11-01T18:59:15.815Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [9866](http://condorpiedra.andes.gob.ar:85/9866/mochawesome.html)
CYPRESS RUN: [8973](https://dashboard.cypress.io/projects/xr7gft/runs/8973/specs)
TEST START: 2023-11-02T12:15:08.196Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [9894](http://condorpiedra.andes.gob.ar:85/9894/mochawesome.html)
CYPRESS RUN: [9001](https://dashboard.cypress.io/projects/xr7gft/runs/9001/specs)
TEST START: 2023-11-10T14:24:52.522Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [9899](http://condorpiedra.andes.gob.ar:85/9899/mochawesome.html)
CYPRESS RUN: [9006](https://dashboard.cypress.io/projects/xr7gft/runs/9006/specs)
TEST START: 2023-11-10T15:19:43.700Z
TOTAL: 370
SUCCESS: 363
FAIL: 5
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [9901](http://condorpiedra.andes.gob.ar:85/9901/mochawesome.html)
CYPRESS RUN: [9008](https://dashboard.cypress.io/projects/xr7gft/runs/9008/specs)
TEST START: 2023-11-10T16:52:09.333Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [9902](http://condorpiedra.andes.gob.ar:85/9902/mochawesome.html)
CYPRESS RUN: [9009](https://dashboard.cypress.io/projects/xr7gft/runs/9009/specs)
TEST START: 2023-11-10T17:05:10.557Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [9908](http://condorpiedra.andes.gob.ar:85/9908/mochawesome.html)
CYPRESS RUN: [9015](https://dashboard.cypress.io/projects/xr7gft/runs/9015/specs)
TEST START: 2023-11-13T11:50:29.425Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [9909](http://condorpiedra.andes.gob.ar:85/9909/mochawesome.html)
CYPRESS RUN: [9016](https://dashboard.cypress.io/projects/xr7gft/runs/9016/specs)
TEST START: 2023-11-13T12:56:30.925Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [9910](http://condorpiedra.andes.gob.ar:85/9910/mochawesome.html)
CYPRESS RUN: [9017](https://dashboard.cypress.io/projects/xr7gft/runs/9017/specs)
TEST START: 2023-11-13T13:07:58.319Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [9966](http://condorpiedra.andes.gob.ar:85/9966/mochawesome.html)
CYPRESS RUN: [9077](https://dashboard.cypress.io/projects/xr7gft/runs/9077/specs)
TEST START: 2023-11-27T11:36:30.582Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Review by Fabio-Ramirez — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [10178](http://condorpiedra.andes.gob.ar:85/10178/mochawesome.html)
CYPRESS RUN: [9286](https://dashboard.cypress.io/projects/xr7gft/runs/9286/specs)
TEST START: 2024-01-04T18:49:48.206Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

**Review by AgosLizzi — APPROVED** [review]

**Pull request merged**
