### PR TITLE
HUDS: incluir ctId labos externos

### PR DESCRIPTION
**Pull request by plammel**
### Requerimiento
 
https://proyectos.andes.gob.ar/browse/EP-195
### Funcionalidad desarrollada 

1. Se incluye concept id de laboratorios externos para listar los mismos en los cdas descargables
2. 
3. 

### UserStory llegó a completarse

- [ ] Si 
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [x] Si Insertar registro en colección configuracionPrestacion: 
```
{
"loinc" :

{ "code" : "34764-1", "codeSystem" : "2.16.840.1.113883.6.1", "codeSystemName" : "LOINC", "displayName" : "General medicine Consult note" }
,
"snomed" : {
        "conceptId" : "3031000246109",
        "term" : "reporte de resultado de test de covid-19 proveniente de SNVS",
        "fsn" : "reporte de resultado de test de covid-19 proveniente de SNVS (procedimiento)",
        "semanticTag" : "procedimiento"
    },
"organizaciones" : []
}
```
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si https://github.com/andes/api/pull/1682
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

### CODE REVIEW

**Comment by martinebucarey** [comment]
USUARIO: plammel  
BUILD NUMBER: [6325](http://condorpiedra.andes.gob.ar:85/6325/mochawesome.html)
CYPRESS RUN: [5216](https://dashboard.cypress.io/projects/xr7gft/runs/5216/specs)
TEST START: 2022-05-03T03:31:55.467Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: plammel  
BUILD NUMBER: [6344](http://condorpiedra.andes.gob.ar:85/6344/mochawesome.html)
CYPRESS RUN: [5229](https://dashboard.cypress.io/projects/xr7gft/runs/5229/specs)
TEST START: 2022-05-03T19:00:50.447Z
TOTAL: 353
SUCCESS: 341
FAIL: 11
SKIPPED: 1

**Review by martinebucarey — APPROVED** [review]

**Review by negro89 — APPROVED** [review]
maravilloso

**Comment by martinebucarey** [comment]
USUARIO: plammel  
BUILD NUMBER: [6441](http://condorpiedra.andes.gob.ar:85/6441/mochawesome.html)
CYPRESS RUN: [5323](https://dashboard.cypress.io/projects/xr7gft/runs/5323/specs)
TEST START: 2022-05-16T18:50:22.194Z
TOTAL: 356
SUCCESS: 352
FAIL: 3
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [6456](http://condorpiedra.andes.gob.ar:85/6456/mochawesome.html)
CYPRESS RUN: [5338](https://dashboard.cypress.io/projects/xr7gft/runs/5338/specs)
TEST START: 2022-05-17T14:32:36.553Z
TOTAL: 406
SUCCESS: 402
FAIL: 3
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [6457](http://condorpiedra.andes.gob.ar:85/6457/mochawesome.html)
CYPRESS RUN: [5339](https://dashboard.cypress.io/projects/xr7gft/runs/5339/specs)
TEST START: 2022-05-17T14:54:57.831Z
TOTAL: 381
SUCCESS: 372
FAIL: 8
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [6458](http://condorpiedra.andes.gob.ar:85/6458/mochawesome.html)
CYPRESS RUN: [5340](https://dashboard.cypress.io/projects/xr7gft/runs/5340/specs)
TEST START: 2022-05-17T15:37:39.900Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: plammel  
BUILD NUMBER: [6523](http://condorpiedra.andes.gob.ar:85/6523/mochawesome.html)
CYPRESS RUN: [5404](https://dashboard.cypress.io/projects/xr7gft/runs/5404/specs)
TEST START: 2022-05-30T18:24:55.845Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

**Pull request merged**
