### PR TITLE
chore(plex): v7.11

### PR DESCRIPTION
**Pull request by liquid36**
### Requerimiento
Actualiza plex a la ultima version para hotfixear el gestor de usuario. 

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

### CODE REVIEW

**Review by palita1991 — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [3033](http://condorpiedra.andes.gob.ar:85/3033/mochawesome.html)
CYPRESS RUN: [2160](https://dashboard.cypress.io/projects/xr7gft/runs/2160/specs)
TEST START: 2021-01-06T17:36:51.801Z
TOTAL: 353
SUCCESS: 350
FAIL: 3
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [3034](http://condorpiedra.andes.gob.ar:85/3034/mochawesome.html)
CYPRESS RUN: [2161](https://dashboard.cypress.io/projects/xr7gft/runs/2161/specs)
TEST START: 2021-01-06T17:47:42.907Z
TOTAL: 353
SUCCESS: 351
FAIL: 2
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [3035](http://condorpiedra.andes.gob.ar:85/3035/mochawesome.html)
CYPRESS RUN: [2162](https://dashboard.cypress.io/projects/xr7gft/runs/2162/specs)
TEST START: 2021-01-06T18:08:36.463Z
TOTAL: 340
SUCCESS: 339
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [3037](http://condorpiedra.andes.gob.ar:85/3037/mochawesome.html)
CYPRESS RUN: [2164](https://dashboard.cypress.io/projects/xr7gft/runs/2164/specs)
TEST START: 2021-01-06T18:22:31.649Z
TOTAL: 353
SUCCESS: 353
FAIL: 0
SKIPPED: 0

**Pull request merged**
